package schemas.dynamics.microsoft.codeunit.mobilebanking;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 *
 */
@WebService(name = "MobileBanking_Port", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking")
@XmlSeeAlso(
        {
            ObjectFactory.class
        })
public interface MobileBankingPort {

    /**
     *
     * @param amount
     * @param endDate
     * @param description
     * @param emailaddress
     * @param accountNumber
     * @param message
     * @param phoneNo
     * @param transactionType
     * @param customerType
     * @param balance
     * @param requestId
     * @param fKey
     * @param response
     * @param crAccount
     * @param trnxCharges
     * @param startTime
     * @param endTime
     * @param responseMessage
     * @param startDate
     * @param status
     */
    @WebMethod(operationName = "Spotcash", action = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking:Spotcash")
    @RequestWrapper(localName = "Spotcash", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.Spotcash")
    @ResponseWrapper(localName = "Spotcash_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.SpotcashResult")
    public void spotcash(
            @WebParam(name = "request_id", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> requestId,
            @WebParam(name = "phone_no", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> phoneNo,
            @WebParam(name = "transaction_type", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<Integer> transactionType,
            @WebParam(name = "amount", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> amount,
            @WebParam(name = "trnx_charges", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> trnxCharges,
            @WebParam(name = "account__number", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> accountNumber,
            @WebParam(name = "cr_account", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> crAccount,
            @WebParam(name = "status", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> status,
            @WebParam(name = "f_key", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> fKey,
            @WebParam(name = "balance", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> balance,
            @WebParam(name = "message", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> message,
            @WebParam(name = "response", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> response,
            @WebParam(name = "response_message", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseMessage,
            @WebParam(name = "customerType", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> customerType,
            @WebParam(name = "description", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> description,
            @WebParam(name = "startDate", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> startDate,
            @WebParam(name = "endDate", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> endDate,
            @WebParam(name = "startTime", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> startTime,
            @WebParam(name = "endTime", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> endTime,
            @WebParam(name = "emailaddress", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> emailaddress);

    /**
     *
     * @param spotCashID
     * @param mPESAID
     * @param errorMessage
     * @param responseMessage
     * @param phoneNo
     * @param responseCode
     */
    @WebMethod(operationName = "UpdateMPESADetails", action = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking:UpdateMPESADetails")
    @RequestWrapper(localName = "UpdateMPESADetails", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.UpdateMPESADetails")
    @ResponseWrapper(localName = "UpdateMPESADetails_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.UpdateMPESADetailsResult")
    public void updateMPESADetails(
            @WebParam(name = "spotCashID", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> spotCashID,
            @WebParam(name = "mPESAID", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> mPESAID,
            @WebParam(name = "phoneNo", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> phoneNo,
            @WebParam(name = "responseCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseCode,
            @WebParam(name = "responseMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseMessage,
            @WebParam(name = "errorMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> errorMessage);

    /**
     *
     * @param passportPhoto
     * @param backID
     * @param occupation
     * @param returnValue
     * @param gender
     * @param signature
     * @param applicationNo
     * @param phoneNo
     * @param refererPhoneNo
     * @param responseCode
     * @param frontID
     * @param surname
     * @param hudumaNumber
     * @param residence
     * @param email
     * @param address
     * @param errorMessage
     * @param dateOfBirth
     * @param iDNo
     * @param pinNo
     * @param branchCode
     * @param firstName
     * @param middleName
     * @param responseMessage
     * @param maritalStatus
     * @param alternativeContact
     */
    @WebMethod(operationName = "MemberRegistration", action = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking:MemberRegistration")
    @RequestWrapper(localName = "MemberRegistration", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.MemberRegistration")
    @ResponseWrapper(localName = "MemberRegistration_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.MemberRegistrationResult")
    public void memberRegistration(
            @WebParam(name = "iDNo", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> iDNo,
            @WebParam(name = "firstName", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> firstName,
            @WebParam(name = "middleName", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> middleName,
            @WebParam(name = "branchCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> branchCode,
            @WebParam(name = "surname", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> surname,
            @WebParam(name = "pinNo", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> pinNo,
            @WebParam(name = "address", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> address,
            @WebParam(name = "gender", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> gender,
            @WebParam(name = "occupation", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> occupation,
            @WebParam(name = "phoneNo", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> phoneNo,
            @WebParam(name = "email", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> email,
            @WebParam(name = "passportPhoto", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> passportPhoto,
            @WebParam(name = "frontID", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> frontID,
            @WebParam(name = "backID", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> backID,
            @WebParam(name = "signature", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> signature,
            @WebParam(name = "dateOfBirth", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> dateOfBirth,
            @WebParam(name = "maritalStatus", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> maritalStatus,
            @WebParam(name = "applicationNo", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> applicationNo,
            @WebParam(name = "hudumaNumber", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> hudumaNumber,
            @WebParam(name = "residence", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> residence,
            @WebParam(name = "alternativeContact", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> alternativeContact,
            @WebParam(name = "refererPhoneNo", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> refererPhoneNo,
            @WebParam(name = "responseCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseCode,
            @WebParam(name = "responseMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseMessage,
            @WebParam(name = "errorMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> errorMessage,
            @WebParam(name = "return_value", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.OUT) Holder<Integer> returnValue);

    /**
     *
     * @param mobilePhoneNo
     * @param returnValue
     * @param errorMessage
     * @param responseMessage
     * @param responseCode
     */
    @WebMethod(operationName = "GetMemberAccounts", action = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking:GetMemberAccounts")
    @RequestWrapper(localName = "GetMemberAccounts", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GetMemberAccounts")
    @ResponseWrapper(localName = "GetMemberAccounts_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GetMemberAccountsResult")
    public void getMemberAccounts(
            @WebParam(name = "mobilePhoneNo", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> mobilePhoneNo,
            @WebParam(name = "responseCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseCode,
            @WebParam(name = "responseMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseMessage,
            @WebParam(name = "errorMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> errorMessage,
            @WebParam(name = "return_value", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.OUT) Holder<Integer> returnValue);

    /**
     *
     * @param errorMessage
     * @param accountNumber
     * @param responseMessage
     * @param responseCode
     */
    @WebMethod(operationName = "ValidateAccountDetails", action = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking:ValidateAccountDetails")
    @RequestWrapper(localName = "ValidateAccountDetails", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.ValidateAccountDetails")
    @ResponseWrapper(localName = "ValidateAccountDetails_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.ValidateAccountDetailsResult")
    public void validateAccountDetails(
            @WebParam(name = "accountNumber", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> accountNumber,
            @WebParam(name = "responseCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseCode,
            @WebParam(name = "responseMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseMessage,
            @WebParam(name = "errorMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> errorMessage);

    /**
     *
     * @param returnValue
     * @param errorMessage
     * @param idNumber
     * @param responseMessage
     * @param responseCode
     */
    @WebMethod(operationName = "GetMemberImage", action = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking:GetMemberImage")
    @RequestWrapper(localName = "GetMemberImage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GetMemberImage")
    @ResponseWrapper(localName = "GetMemberImage_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GetMemberImageResult")
    public void getMemberImage(
            @WebParam(name = "idNumber", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> idNumber,
            @WebParam(name = "responseCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseCode,
            @WebParam(name = "responseMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseMessage,
            @WebParam(name = "errorMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> errorMessage,
            @WebParam(name = "return_value", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.OUT) Holder<Integer> returnValue);

    /**
     *
     * @param mobilePhoneNo
     * @param returnValue
     * @param errorMessage
     * @param responseMessage
     * @param responseCode
     */
    @WebMethod(operationName = "GetLoanAccounts", action = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking:GetLoanAccounts")
    @RequestWrapper(localName = "GetLoanAccounts", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GetLoanAccounts")
    @ResponseWrapper(localName = "GetLoanAccounts_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GetLoanAccountsResult")
    public void getLoanAccounts(
            @WebParam(name = "mobilePhoneNo", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> mobilePhoneNo,
            @WebParam(name = "responseCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseCode,
            @WebParam(name = "responseMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseMessage,
            @WebParam(name = "errorMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> errorMessage,
            @WebParam(name = "return_value", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.OUT) Holder<Integer> returnValue);

    /**
     *
     * @param mobilePhoneNo
     * @param returnValue
     * @param errorMessage
     * @param responseMessage
     * @param responseCode
     */
    @WebMethod(operationName = "GetSavingsAccounts", action = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking:GetSavingsAccounts")
    @RequestWrapper(localName = "GetSavingsAccounts", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GetSavingsAccounts")
    @ResponseWrapper(localName = "GetSavingsAccounts_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GetSavingsAccountsResult")
    public void getSavingsAccounts(
            @WebParam(name = "mobilePhoneNo", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> mobilePhoneNo,
            @WebParam(name = "responseCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseCode,
            @WebParam(name = "responseMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseMessage,
            @WebParam(name = "errorMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> errorMessage,
            @WebParam(name = "return_value", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.OUT) Holder<Integer> returnValue);

    /**
     *
     * @param mobilePhoneNo
     * @param returnValue
     * @param errorMessage
     * @param responseMessage
     * @param responseCode
     */
    @WebMethod(operationName = "GetShareCapitalAccounts", action = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking:GetShareCapitalAccounts")
    @RequestWrapper(localName = "GetShareCapitalAccounts", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GetShareCapitalAccounts")
    @ResponseWrapper(localName = "GetShareCapitalAccounts_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GetShareCapitalAccountsResult")
    public void getShareCapitalAccounts(
            @WebParam(name = "mobilePhoneNo", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> mobilePhoneNo,
            @WebParam(name = "responseCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseCode,
            @WebParam(name = "responseMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseMessage,
            @WebParam(name = "errorMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> errorMessage,
            @WebParam(name = "return_value", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.OUT) Holder<Integer> returnValue);

    /**
     *
     * @param mobilePhoneNo
     * @param returnValue
     * @param errorMessage
     * @param responseMessage
     * @param responseCode
     */
    @WebMethod(operationName = "GetNWDAccounts", action = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking:GetNWDAccounts")
    @RequestWrapper(localName = "GetNWDAccounts", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GetNWDAccounts")
    @ResponseWrapper(localName = "GetNWDAccounts_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GetNWDAccountsResult")
    public void getNWDAccounts(
            @WebParam(name = "mobilePhoneNo", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> mobilePhoneNo,
            @WebParam(name = "responseCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseCode,
            @WebParam(name = "responseMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseMessage,
            @WebParam(name = "errorMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> errorMessage,
            @WebParam(name = "return_value", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.OUT) Holder<Integer> returnValue);

    /**
     *
     * @param mobilePhoneNo
     * @param errorMessage
     * @param responseMessage
     * @param responseCode
     */
    @WebMethod(operationName = "GeteLoanTypes", action = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking:GeteLoanTypes")
    @RequestWrapper(localName = "GeteLoanTypes", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GeteLoanTypes")
    @ResponseWrapper(localName = "GeteLoanTypes_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GeteLoanTypesResult")
    public void geteLoanTypes(
            @WebParam(name = "mobilePhoneNo", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> mobilePhoneNo,
            @WebParam(name = "responseCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseCode,
            @WebParam(name = "responseMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseMessage,
            @WebParam(name = "errorMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> errorMessage);

    /**
     *
     * @param returnValue
     * @param endDate
     * @param errorMessage
     * @param startTime
     * @param emailaddress
     * @param endTime
     * @param accountNumber
     * @param responseMessage
     * @param startDate
     * @param responseCode
     */
    @WebMethod(operationName = "GetStatementTransactions", action = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking:GetStatementTransactions")
    @RequestWrapper(localName = "GetStatementTransactions", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GetStatementTransactions")
    @ResponseWrapper(localName = "GetStatementTransactions_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GetStatementTransactionsResult")
    public void getStatementTransactions(
            @WebParam(name = "accountNumber", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> accountNumber,
            @WebParam(name = "startDate", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<XMLGregorianCalendar> startDate,
            @WebParam(name = "endDate", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<XMLGregorianCalendar> endDate,
            @WebParam(name = "startTime", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<XMLGregorianCalendar> startTime,
            @WebParam(name = "endTime", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<XMLGregorianCalendar> endTime,
            @WebParam(name = "emailaddress", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> emailaddress,
            @WebParam(name = "responseCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseCode,
            @WebParam(name = "responseMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseMessage,
            @WebParam(name = "errorMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> errorMessage,
            @WebParam(name = "return_value", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.OUT) Holder<String> returnValue);

    /**
     *
     * @param eLoanCode
     * @param errorMessage
     * @param responseMessage
     * @param phoneNo
     * @param responseCode
     */
    @WebMethod(operationName = "GetMemberEligibility", action = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking:GetMemberEligibility")
    @RequestWrapper(localName = "GetMemberEligibility", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GetMemberEligibility")
    @ResponseWrapper(localName = "GetMemberEligibility_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GetMemberEligibilityResult")
    public void getMemberEligibility(
            @WebParam(name = "phoneNo", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> phoneNo,
            @WebParam(name = "eLoanCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> eLoanCode,
            @WebParam(name = "responseCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseCode,
            @WebParam(name = "responseMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseMessage,
            @WebParam(name = "errorMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> errorMessage);

    /**
     *
     * @param amount
     * @param eLoanCode
     * @param installments
     * @param requestid
     * @param errorMessage
     * @param responseMessage
     * @param phoneNo
     * @param responseCode
     */
    @WebMethod(operationName = "ApplyLoan", action = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking:ApplyLoan")
    @RequestWrapper(localName = "ApplyLoan", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.ApplyLoan")
    @ResponseWrapper(localName = "ApplyLoan_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.ApplyLoanResult")
    public void applyLoan(
            @WebParam(name = "requestid", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> requestid,
            @WebParam(name = "phoneNo", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> phoneNo,
            @WebParam(name = "eLoanCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> eLoanCode,
            @WebParam(name = "amount", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<BigDecimal> amount,
            @WebParam(name = "installments", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<BigDecimal> installments,
            @WebParam(name = "responseCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseCode,
            @WebParam(name = "responseMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseMessage,
            @WebParam(name = "errorMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> errorMessage);

    /**
     *
     * @param mobilePhoneNo
     * @param errorMessage
     * @param responseMessage
     * @param responseCode
     */
    @WebMethod(operationName = "GetBranchCodes", action = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking:GetBranchCodes")
    @RequestWrapper(localName = "GetBranchCodes", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GetBranchCodes")
    @ResponseWrapper(localName = "GetBranchCodes_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.GetBranchCodesResult")
    public void getBranchCodes(
            @WebParam(name = "mobilePhoneNo", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> mobilePhoneNo,
            @WebParam(name = "responseCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseCode,
            @WebParam(name = "responseMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseMessage,
            @WebParam(name = "errorMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> errorMessage);

    /**
     *
     * @param firstName
     * @param lastName
     * @param gender
     * @param errorMessage
     * @param location
     * @param introducerPhone
     * @param responseMessage
     * @param phoneNo
     * @param responseCode
     */
    @WebMethod(operationName = "ReferAFriend", action = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking:ReferAFriend")
    @RequestWrapper(localName = "ReferAFriend", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.ReferAFriend")
    @ResponseWrapper(localName = "ReferAFriend_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.ReferAFriendResult")
    public void referAFriend(
            @WebParam(name = "firstName", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> firstName,
            @WebParam(name = "lastName", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> lastName,
            @WebParam(name = "phoneNo", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> phoneNo,
            @WebParam(name = "gender", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> gender,
            @WebParam(name = "location", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> location,
            @WebParam(name = "introducerPhone", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> introducerPhone,
            @WebParam(name = "responseCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseCode,
            @WebParam(name = "responseMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseMessage,
            @WebParam(name = "errorMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> errorMessage);

    /**
     *
     * @param requestID
     * @param errorMessage
     * @param responseMessage
     * @param responseCode
     */
    @WebMethod(operationName = "ProcessReversal", action = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking:ProcessReversal")
    @RequestWrapper(localName = "ProcessReversal", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.ProcessReversal")
    @ResponseWrapper(localName = "ProcessReversal_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.ProcessReversalResult")
    public void processReversal(
            @WebParam(name = "requestID", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> requestID,
            @WebParam(name = "responseCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseCode,
            @WebParam(name = "responseMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseMessage,
            @WebParam(name = "errorMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> errorMessage);

    /**
     *
     * @param errorMessage
     * @param newMembersPayload
     * @param responseMessage
     * @param responseCode
     */
    @WebMethod(operationName = "SpotcashRegistration", action = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking:SpotcashRegistration")
    @RequestWrapper(localName = "SpotcashRegistration", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.SpotcashRegistration")
    @ResponseWrapper(localName = "SpotcashRegistration_Result", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", className = "schemas.dynamics.microsoft.codeunit.mobilebanking.SpotcashRegistrationResult")
    public void spotcashRegistration(
            @WebParam(name = "responseCode", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseCode,
            @WebParam(name = "responseMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> responseMessage,
            @WebParam(name = "errorMessage", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> errorMessage,
            @WebParam(name = "newMembersPayload", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", mode = WebParam.Mode.INOUT) Holder<String> newMembersPayload);

}
