package schemas.dynamics.microsoft.codeunit.mobilebanking;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "MobileBanking", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/MobileBanking", wsdlLocation = "file:/D:/Applications/Kenya/NAWIRI/WebApplication2/src/conf/xml-resources/web-services/VXService/wsdl/MobileBanking.wsdl")
public class MobileBanking
        extends Service {

    private final static URL MOBILEBANKING_WSDL_LOCATION;
    private final static WebServiceException MOBILEBANKING_EXCEPTION;
    private final static QName MOBILEBANKING_QNAME = new QName("urn:microsoft-dynamics-schemas/codeunit/MobileBanking", "MobileBanking");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Applications/Kenya/NAWIRI/WebApplication2/src/conf/xml-resources/web-services/VXService/wsdl/MobileBanking.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MOBILEBANKING_WSDL_LOCATION = url;
        MOBILEBANKING_EXCEPTION = e;
    }

    public MobileBanking() {
        super(__getWsdlLocation(), MOBILEBANKING_QNAME);
    }

    public MobileBanking(WebServiceFeature... features) {
        super(__getWsdlLocation(), MOBILEBANKING_QNAME, features);
    }

    public MobileBanking(URL wsdlLocation) {
        super(wsdlLocation, MOBILEBANKING_QNAME);
    }

    public MobileBanking(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MOBILEBANKING_QNAME, features);
    }

    public MobileBanking(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MobileBanking(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return returns MobileBankingPort
     */
    @WebEndpoint(name = "MobileBanking_Port")
    public MobileBankingPort getMobileBankingPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/codeunit/MobileBanking", "MobileBanking_Port"), MobileBankingPort.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in the
     * <code>features</code> parameter will have their default values.
     * @return returns MobileBankingPort
     */
    @WebEndpoint(name = "MobileBanking_Port")
    public MobileBankingPort getMobileBankingPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/codeunit/MobileBanking", "MobileBanking_Port"), MobileBankingPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MOBILEBANKING_EXCEPTION != null) {
            throw MOBILEBANKING_EXCEPTION;
        }
        return MOBILEBANKING_WSDL_LOCATION;
    }

}
