
package com.neptunesoftwareplc.ci.transfer.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransferService", targetNamespace = "http://service.transfer.ci.neptunesoftwareplc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransferService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.neptunesoftwareplc.ci.transfer.service.FundsTransferOutputData
     * @throws CIException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "postDepositToGLAccountTransfer", targetNamespace = "http://service.transfer.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.transfer.service.PostDepositToGLAccountTransfer")
    @ResponseWrapper(localName = "postDepositToGLAccountTransferResponse", targetNamespace = "http://service.transfer.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.transfer.service.PostDepositToGLAccountTransferResponse")
    public FundsTransferOutputData postDepositToGLAccountTransfer(
        @WebParam(name = "arg0", targetNamespace = "")
        FundsTransferRequestData arg0)
        throws CIException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.neptunesoftwareplc.ci.transfer.service.FundsTransferOutputData
     * @throws CIException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "internalDepositAccountTransfer", targetNamespace = "http://service.transfer.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.transfer.service.InternalDepositAccountTransfer")
    @ResponseWrapper(localName = "internalDepositAccountTransferResponse", targetNamespace = "http://service.transfer.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.transfer.service.InternalDepositAccountTransferResponse")
    public FundsTransferOutputData internalDepositAccountTransfer(
        @WebParam(name = "arg0", targetNamespace = "")
        FundsTransferRequestData arg0)
        throws CIException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.neptunesoftwareplc.ci.transfer.service.DepositTxnEnquiryOutputCIData
     * @throws CIException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDepositMiniStatement", targetNamespace = "http://service.transfer.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.transfer.service.FindDepositMiniStatement")
    @ResponseWrapper(localName = "findDepositMiniStatementResponse", targetNamespace = "http://service.transfer.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.transfer.service.FindDepositMiniStatementResponse")
    public DepositTxnEnquiryOutputCIData findDepositMiniStatement(
        @WebParam(name = "arg0", targetNamespace = "")
        CiRequestBaseObject arg0)
        throws CIException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.neptunesoftwareplc.ci.transfer.service.CashOutputData
     * @throws CIException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "depositCashWithDrawerUpdate", targetNamespace = "http://service.transfer.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.transfer.service.DepositCashWithDrawerUpdate")
    @ResponseWrapper(localName = "depositCashWithDrawerUpdateResponse", targetNamespace = "http://service.transfer.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.transfer.service.DepositCashWithDrawerUpdateResponse")
    public CashOutputData depositCashWithDrawerUpdate(
        @WebParam(name = "arg0", targetNamespace = "")
        CashRequestData arg0)
        throws CIException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.neptunesoftwareplc.ci.transfer.service.CashOutputData
     * @throws CIException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "withdrawCashWithDrawerUpdate", targetNamespace = "http://service.transfer.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.transfer.service.WithdrawCashWithDrawerUpdate")
    @ResponseWrapper(localName = "withdrawCashWithDrawerUpdateResponse", targetNamespace = "http://service.transfer.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.transfer.service.WithdrawCashWithDrawerUpdateResponse")
    public CashOutputData withdrawCashWithDrawerUpdate(
        @WebParam(name = "arg0", targetNamespace = "")
        CashRequestData arg0)
        throws CIException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.neptunesoftwareplc.ci.transfer.service.FundsTransferOutputData
     * @throws CIException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "postGLToDepositAccountTransfer", targetNamespace = "http://service.transfer.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.transfer.service.PostGLToDepositAccountTransfer")
    @ResponseWrapper(localName = "postGLToDepositAccountTransferResponse", targetNamespace = "http://service.transfer.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.transfer.service.PostGLToDepositAccountTransferResponse")
    public FundsTransferOutputData postGLToDepositAccountTransfer(
        @WebParam(name = "arg0", targetNamespace = "")
        FundsTransferRequestData arg0)
        throws CIException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.neptunesoftwareplc.ci.transfer.service.GlTransferOutputData
     * @throws CIException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "postGLToGLTransfer", targetNamespace = "http://service.transfer.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.transfer.service.PostGLToGLTransfer")
    @ResponseWrapper(localName = "postGLToGLTransferResponse", targetNamespace = "http://service.transfer.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.transfer.service.PostGLToGLTransferResponse")
    public GlTransferOutputData postGLToGLTransfer(
        @WebParam(name = "arg0", targetNamespace = "")
        GlTransferRequestData arg0)
        throws CIException_Exception
    ;

}
