CREATE OR REPLACE PACKAGE "EB_PACKAGE"
AS
   TYPE REF_CURSOR IS REF CURSOR;
END EB_PACKAGE;

DROP TABLE PHC_WAIVER CASCADE CONSTRAINTS;

CREATE TABLE PHC_WAIVER
(
  REC_ID       NUMBER                           NOT NULL,
  PARENT       VARCHAR2(5 BYTE)                 NOT NULL,
  PROD_ID      INTEGER                          NOT NULL,
  MATCH_ACCT   VARCHAR2(2 BYTE),
  WAIVED_PERC  NUMBER(38,10),
  CONDITION    VARCHAR2(5 BYTE),
  THRESHOLD    NUMBER(38,10)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHC_TIER CASCADE CONSTRAINTS;

CREATE TABLE PHC_TIER
(
  REC_ID      NUMBER                            NOT NULL,
  TYPE        VARCHAR2(5 BYTE),
  PARENT      VARCHAR2(5 BYTE)                  NOT NULL,
  TIER_MAX    NUMBER(38,10),
  TIER_VALUE  NUMBER(38,10)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHB_PAYMENT CASCADE CONSTRAINTS;

CREATE TABLE PHB_PAYMENT
(
  REC_ID        NUMBER                          NOT NULL,
  CREATE_DT     DATE,
  MODULE        VARCHAR2(20 BYTE),
  TXN_CD        VARCHAR2(3 BYTE)                NOT NULL,
  TYPE          VARCHAR2(2 BYTE)                NOT NULL,
  DESCRIPTION   VARCHAR2(60 BYTE),
  CODE_FIELD    NUMBER,
  CODE          VARCHAR2(25 BYTE),
  POSITION      VARCHAR2(10 BYTE),
  DETAIL_FIELD  NUMBER,
  ACCOUNT       VARCHAR2(25 BYTE),
  SYS_USER      VARCHAR2(60 BYTE),
  SYS_DATE      DATE,
  REC_ST        VARCHAR2(1 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE PHT_ACCOUNT
 DROP PRIMARY KEY CASCADE;

DROP TABLE PHT_ACCOUNT CASCADE CONSTRAINTS;

CREATE TABLE PHT_ACCOUNT
(
  REC_ID    NUMBER                              NOT NULL,
  PARENT    VARCHAR2(20 BYTE)                   NOT NULL,
  CURRENCY  VARCHAR2(4 BYTE),
  ACCOUNT   VARCHAR2(35 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHT_TERMINAL CASCADE CONSTRAINTS;

CREATE TABLE PHT_TERMINAL
(
  REC_CD    VARCHAR2(20 BYTE)                   NOT NULL,
  MODULE    VARCHAR2(20 BYTE)                   NOT NULL,
  SCHEME    VARCHAR2(25 BYTE)                   NOT NULL,
  LOCATION  VARCHAR2(120 BYTE)                  NOT NULL,
  OPERATOR  VARCHAR2(15 BYTE)                   NOT NULL,
  BU_NO     VARCHAR2(4 BYTE)                    NOT NULL,
  SYS_DATE  DATE,
  SYS_USER  VARCHAR2(60 BYTE),
  REC_ST    VARCHAR2(20 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHG_WF_LOG CASCADE CONSTRAINTS;

CREATE TABLE PHG_WF_LOG
(
  REC_ID      NUMBER                            NOT NULL,
  CREATE_DT   DATE,
  TXN_REF     VARCHAR2(40 BYTE),
  CHANNEL_ID  INTEGER,
  ACCESS_CD   VARCHAR2(20 BYTE),
  GROUP_NO    VARCHAR2(20 BYTE),
  MEMBER_NO   VARCHAR2(20 BYTE),
  ROLE        VARCHAR2(25 BYTE),
  ACCOUNT     VARCHAR2(25 BYTE),
  CURRENCY    VARCHAR2(4 BYTE),
  AMOUNT      NUMBER(16,2),
  DETAIL      VARCHAR2(50 BYTE),
  REC_ST      CHAR(1 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHL_ENRL_LOG CASCADE CONSTRAINTS;

CREATE TABLE PHL_ENRL_LOG
(
  REC_ID      NUMBER                            NOT NULL,
  CREATE_DT   DATE,
  CHANNEL_ID  INTEGER,
  ADDRESS     VARCHAR2(25 BYTE),
  ACCESS_CD   VARCHAR2(20 BYTE),
  CUST_NO     VARCHAR2(20 BYTE),
  ACCOUNT     VARCHAR2(25 BYTE),
  ALIAS       VARCHAR2(50 BYTE),
  ROLE        VARCHAR2(20 BYTE),
  TYPE        VARCHAR2(15 BYTE),
  STATE       VARCHAR2(15 BYTE),
  RESULT      VARCHAR2(20 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHL_BANK CASCADE CONSTRAINTS;

CREATE TABLE PHL_BANK
(
  BIN              VARCHAR2(10 BYTE)            NOT NULL,
  CREATE_DT        DATE,
  BANK_NAME        VARCHAR2(60 BYTE),
  LORO_LEDGER      VARCHAR2(25 BYTE),
  TRANSFER_LEDGER  VARCHAR2(25 BYTE),
  SUSPENSE_LEDGER  VARCHAR2(25 BYTE),
  SYS_USER         VARCHAR2(60 BYTE),
  SYS_DATE         DATE,
  REC_ST           VARCHAR2(1 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHC_SPLIT CASCADE CONSTRAINTS;

CREATE TABLE PHC_SPLIT
(
  REC_ID       NUMBER                           NOT NULL,
  TXN_DT       DATE,
  TXN_REF      VARCHAR2(40 BYTE)                NOT NULL,
  MODULE       VARCHAR2(20 BYTE)                NOT NULL,
  DR_ACCT      VARCHAR2(30 BYTE),
  CR_ACCT      VARCHAR2(30 BYTE),
  CURRENCY     VARCHAR2(3 BYTE),
  AMOUNT       NUMBER(16,2),
  DESCRIPTION  VARCHAR2(100 BYTE),
  REVERSAL     VARCHAR2(1 BYTE),
  REC_ST       VARCHAR2(1 BYTE),
  LUMP         VARCHAR2(1 BYTE),
  FIELD        VARCHAR2(1 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
           )
LOGGING
PARTITION BY RANGE (TXN_DT)
INTERVAL( NUMTOYMINTERVAL(3, 'MONTH'))
(  
  PARTITION PHC_SPLIT_Q1_2018 VALUES LESS THAN (TO_DATE(' 2018-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PHC_SPLIT_Q2_2018 VALUES LESS THAN (TO_DATE(' 2018-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PHC_SPLIT_Q3_2018 VALUES LESS THAN (TO_DATE(' 2018-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PHC_SPLIT_Q4_2018 VALUES LESS THAN (TO_DATE(' 2019-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PHC_SPLIT_Q1_2019 VALUES LESS THAN (TO_DATE(' 2019-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PHC_SPLIT_Q2_2019 VALUES LESS THAN (TO_DATE(' 2019-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PHC_SPLIT_Q3_2019 VALUES LESS THAN (TO_DATE(' 2019-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PHC_SPLIT_Q4_2019 VALUES LESS THAN (TO_DATE(' 2020-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PHC_SPLIT_Q1_2020 VALUES LESS THAN (TO_DATE(' 2020-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PHC_SPLIT_Q2_2020 VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PHC_SPLIT_Q3_2020 VALUES LESS THAN (TO_DATE(' 2020-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PHC_SPLIT_Q4_2020 VALUES LESS THAN (TO_DATE(' 2021-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               )
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHC_SCHEME CASCADE CONSTRAINTS;

CREATE TABLE PHC_SCHEME
(
  REC_CD       VARCHAR2(10 BYTE)                NOT NULL,
  CREATE_DT    DATE,
  MODULE       VARCHAR2(20 BYTE),
  DESCRIPTION  VARCHAR2(60 BYTE),
  SYS_USER     VARCHAR2(60 BYTE),
  SYS_DATE     DATE,
  REC_ST       VARCHAR2(1 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHL_FRIEND CASCADE CONSTRAINTS;

CREATE TABLE PHL_FRIEND
(
  REC_ID      NUMBER                            NOT NULL,
  CREATE_DT   DATE,
  MODULE      VARCHAR2(10 BYTE),
  FIRST_NM    VARCHAR2(50 BYTE)                 NOT NULL,
  LAST_NM     VARCHAR2(50 BYTE)                 NOT NULL,
  PHONE_NO    VARCHAR2(15 BYTE)                 NOT NULL,
  GENDER      VARCHAR2(10 BYTE),
  LOCATION    VARCHAR2(50 BYTE),
  INTRODUCER  VARCHAR2(15 BYTE),
  REC_ST      VARCHAR2(1 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE PHS_TASK
 DROP PRIMARY KEY CASCADE;

DROP TABLE PHS_TASK CASCADE CONSTRAINTS;

CREATE TABLE PHS_TASK
(
  REC_ID       NUMBER                           NOT NULL,
  REC_CD       VARCHAR2(10 BYTE)                NOT NULL,
  CREATE_DT    DATE,
  DOCUMENT     VARCHAR2(3 BYTE),
  RANGE        VARCHAR2(2 BYTE),
  DESCRIPTION  VARCHAR2(60 BYTE),
  RUN_TIME     VARCHAR2(25 BYTE),
  CHARGE       VARCHAR2(60 BYTE),
  CYCLE        VARCHAR2(25 BYTE),
  NEXT_DATE    DATE,
  LAST_DATE    DATE,
  EXPIRY_DATE  DATE,
  FILTER_BY    VARCHAR2(10 BYTE),
  REC_ST       VARCHAR2(1 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE PHL_TXN_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE PHL_TXN_LOG CASCADE CONSTRAINTS;

CREATE TABLE PHL_TXN_LOG
(
  REC_ID         NUMBER                         NOT NULL,
  TXN_REF        VARCHAR2(40 BYTE),
  TXN_DATE       DATE                           NOT NULL,
  CHANNEL_ID     INTEGER,
  MODULE         VARCHAR2(20 BYTE),
  CLIENT         VARCHAR2(20 BYTE),
  TXN_CODE       VARCHAR2(6 BYTE),
  TXN_TYPE       VARCHAR2(30 BYTE),
  BU_ID          NUMBER,
  ACQUIRER       VARCHAR2(10 BYTE),
  TERMINAL       VARCHAR2(20 BYTE),
  ADVICE         VARCHAR2(1 BYTE),
  ONUS           VARCHAR2(1 BYTE),
  ACCESS_CD      VARCHAR2(19 BYTE),
  ACCOUNT        VARCHAR2(25 BYTE),
  CONTRA         VARCHAR2(25 BYTE),
  CURRENCY       VARCHAR2(4 BYTE),
  AMOUNT         NUMBER(16,2),
  DESCRIPTION    VARCHAR2(100 BYTE),
  DETAIL         VARCHAR2(100 BYTE),
  RECEIPT        VARCHAR2(35 BYTE),
  CHARGE_LEDGER  VARCHAR2(30 BYTE),
  CHARGE         NUMBER(16,2),
  TXN_ID         VARCHAR2(25 BYTE),
  CHG_ID         VARCHAR2(25 BYTE),
  BALANCE        NUMBER(16,2),
  XAPI_CODE      VARCHAR2(50 BYTE),
  RESULT         VARCHAR2(35 BYTE),
  RESP_CODE      VARCHAR2(15 BYTE),
  CALLER         BLOB,
  REC_ST         VARCHAR2(1 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (CALLER) STORE AS SECUREFILE 
      ( TABLESPACE NSNDAT01 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        NOCACHE
        INDEX       (
          TABLESPACE NSNDAT01
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          104K
                    NEXT             1M
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHS_EST_LOG CASCADE CONSTRAINTS;

CREATE TABLE PHS_EST_LOG
(
  REC_ID     NUMBER                             NOT NULL,
  CREATE_DT  DATE,
  TASK       VARCHAR2(5 BYTE),
  ACCOUNT    VARCHAR2(25 BYTE),
  START_DT   DATE,
  END_DT     DATE,
  ADDRESS    VARCHAR2(750 BYTE),
  CHARGE     NUMBER(16,2),
  CHG_ID     VARCHAR2(25 BYTE),
  REC_ST     VARCHAR2(1 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHC_DEDUCTION CASCADE CONSTRAINTS;

CREATE TABLE PHC_DEDUCTION
(
  REC_ID       NUMBER                           NOT NULL,
  PARENT       VARCHAR2(5 BYTE)                 NOT NULL,
  BASIS        VARCHAR2(2 BYTE)                 NOT NULL,
  DESCRIPTION  VARCHAR2(75 BYTE),
  ACCOUNT      VARCHAR2(25 BYTE),
  TYPE         VARCHAR2(2 BYTE),
  VALUE        NUMBER(38,10)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE PHC_VALUE
 DROP PRIMARY KEY CASCADE;

DROP TABLE PHC_VALUE CASCADE CONSTRAINTS;

CREATE TABLE PHC_VALUE
(
  REC_ID     NUMBER                             NOT NULL,
  PARENT     VARCHAR2(10 BYTE)                  NOT NULL,
  CURRENCY   VARCHAR2(4 BYTE)                   NOT NULL,
  TYPE       VARCHAR2(35 BYTE),
  MIN_VALUE  NUMBER(38,10),
  MAX_VALUE  NUMBER(38,10),
  VALUE      NUMBER(38,10)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHA_ALERTS CASCADE CONSTRAINTS;

CREATE TABLE PHA_ALERTS
(
  REC_ID      NUMBER                            NOT NULL,
  CREATE_DT   DATE,
  CODE        VARCHAR2(3 BYTE),
  TYPE        VARCHAR2(3 BYTE),
  TXN_ID      NUMBER,
  BU_ID       NUMBER,
  CUST_ID     NUMBER,
  CUST_NAME   VARCHAR2(120 BYTE),
  TXN_DATE    DATE,
  ACCT_NO     VARCHAR2(60 BYTE),
  CONTRA      VARCHAR2(60 BYTE),
  CURRENCY    VARCHAR2(10 BYTE),
  TXN_AMT     NUMBER(38,10),
  TXN_CHG     NUMBER(38,10),
  TXN_DESC    VARCHAR2(300 BYTE),
  BALANCE     NUMBER(38,10),
  CHRG_ACCT   VARCHAR2(60 BYTE),
  CHRG_AMT    NUMBER(38,10),
  CONTACT     VARCHAR2(100 BYTE),
  ORIGINATOR  VARCHAR2(100 BYTE),
  SCHEME_ID   NUMBER,
  ACCESS_CD   VARCHAR2(30 BYTE),
  PASSWORD    VARCHAR2(30 BYTE),
  CHG_ID      VARCHAR2(25 BYTE),
  REC_ST      CHAR(1 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHL_TEMPLATE CASCADE CONSTRAINTS;

CREATE TABLE PHL_TEMPLATE
(
  REC_ID    NUMBER                              NOT NULL,
  PARENT    VARCHAR2(10 BYTE)                   NOT NULL,
  MODULE    VARCHAR2(20 BYTE)                   NOT NULL,
  LANGUAGE  VARCHAR2(5 BYTE),
  TEMPLATE  VARCHAR2(250 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE PHA_ALERT
 DROP PRIMARY KEY CASCADE;

DROP TABLE PHA_ALERT CASCADE CONSTRAINTS;

CREATE TABLE PHA_ALERT
(
  REC_ID       NUMBER                           NOT NULL,
  CODE         VARCHAR2(10 BYTE)                NOT NULL,
  CREATE_DT    DATE,
  TYPE         VARCHAR2(3 BYTE),
  DESCRIPTION  VARCHAR2(60 BYTE),
  PRIORITY     INTEGER,
  MIN_AMT      NUMBER(38,10),
  RUN_TIME     VARCHAR2(25 BYTE),
  CHRG_CODE    VARCHAR2(60 BYTE),
  FREQUENCY    VARCHAR2(25 BYTE),
  DAYS         VARCHAR2(50 BYTE),
  NEXT_DATE    DATE,
  LAST_DATE    DATE,
  EXPIRY_DATE  DATE,
  FILTER_BY    VARCHAR2(10 BYTE),
  REC_ST       VARCHAR2(1 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHA_MESSAGE CASCADE CONSTRAINTS;

CREATE TABLE PHA_MESSAGE
(
  REC_ID     NUMBER                             NOT NULL,
  CREATE_DT  DATE,
  PARENT     NUMBER,
  CODE       VARCHAR2(3 BYTE),
  CUST_ID    NUMBER,
  CONTACT    VARCHAR2(100 BYTE),
  MESSAGE    VARCHAR2(250 BYTE),
  RESULT     VARCHAR2(35 BYTE),
  RESP_ID    VARCHAR2(35 BYTE),
  REC_ST     CHAR(1 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE PHC_CHARGE
 DROP PRIMARY KEY CASCADE;

DROP TABLE PHC_CHARGE CASCADE CONSTRAINTS;

CREATE TABLE PHC_CHARGE
(
  REC_ID       NUMBER                           NOT NULL,
  REC_CD       VARCHAR2(10 BYTE)                NOT NULL,
  CREATE_DT    DATE,
  SCHEME       VARCHAR2(25 BYTE),
  DESCRIPTION  VARCHAR2(60 BYTE),
  ACCOUNT      VARCHAR2(25 BYTE),
  LEDGER       VARCHAR2(25 BYTE),
  BASIS        VARCHAR2(1 BYTE),
  SYS_USER     VARCHAR2(60 BYTE),
  SYS_DATE     DATE,
  REC_ST       VARCHAR2(1 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHU_USER CASCADE CONSTRAINTS;

CREATE TABLE PHU_USER
(
  EMP_NO      VARCHAR2(10 BYTE)                 NOT NULL,
  CREATE_DT   DATE,
  LOGIN_ID    VARCHAR2(60 BYTE),
  STAFF_NAME  VARCHAR2(60 BYTE),
  SYS_USER    VARCHAR2(60 BYTE),
  SYS_DATE    DATE,
  REC_ST      VARCHAR2(1 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHL_FILTER CASCADE CONSTRAINTS;

CREATE TABLE PHL_FILTER
(
  REC_ID  NUMBER                                NOT NULL,
  PARENT  VARCHAR2(10 BYTE)                     NOT NULL,
  MODULE  VARCHAR2(20 BYTE)                     NOT NULL,
  FILTER  VARCHAR2(2100 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHU_ROLE CASCADE CONSTRAINTS;

CREATE TABLE PHU_ROLE
(
  EMP_NO  VARCHAR2(10 BYTE)                     NOT NULL,
  ROLE    VARCHAR2(5 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHL_SETTING CASCADE CONSTRAINTS;

CREATE TABLE PHL_SETTING
(
  REC_ID       NUMBER,
  MODULE       VARCHAR2(15 BYTE),
  CODE         VARCHAR2(35 BYTE)                NOT NULL,
  VALUE        VARCHAR2(1000 BYTE),
  DESCRIPTION  VARCHAR2(150 BYTE),
  SYS_USER     VARCHAR2(60 BYTE),
  SYS_DATE     DATE
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PHL_LIST CASCADE CONSTRAINTS;

CREATE TABLE PHL_LIST
(
  REC_ID  NUMBER                                NOT NULL,
  PARENT  NUMBER                                NOT NULL,
  VALUE   VARCHAR2(100 BYTE)
)
TABLESPACE NSNDAT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PHA_ALERTS_IDX ON PHA_ALERTS
(CREATE_DT, TYPE, REC_ST)
LOGGING
TABLESPACE NSNDAT01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          96M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PHA_ALERTS_PK ON PHA_ALERTS
(REC_ID)
LOGGING
TABLESPACE NSNDAT01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PHA_ALERT_PK ON PHA_ALERT
(REC_ID)
LOGGING
TABLESPACE NSNDAT01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PHC_CHARGE_PK ON PHC_CHARGE
(REC_ID)
LOGGING
TABLESPACE NSNDAT01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PHC_SCHEME_PK ON PHC_SCHEME
(REC_CD)
LOGGING
TABLESPACE NSNDAT01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PHC_VALUE_PK ON PHC_VALUE
(REC_ID)
LOGGING
TABLESPACE NSNDAT01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PHL_BANK_PK ON PHL_BANK
(BIN)
LOGGING
TABLESPACE NSNDAT01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PHL_TXN_LOG_PK ON PHL_TXN_LOG
(REC_ID)
LOGGING
TABLESPACE NSNDAT01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PHS_TASK_PK ON PHS_TASK
(REC_ID)
LOGGING
TABLESPACE NSNDAT01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PHT_ACCOUNT_PK ON PHT_ACCOUNT
(REC_ID)
LOGGING
TABLESPACE NSNDAT01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PHU_USER_PK ON PHU_USER
(EMP_NO)
LOGGING
TABLESPACE NSNDAT01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PHT_ACCOUNT ADD (
  CONSTRAINT PHT_ACCOUNT_PK
 PRIMARY KEY
 (REC_ID)
    USING INDEX 
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE PHS_TASK ADD (
  CONSTRAINT PHS_TASK_PK
 PRIMARY KEY
 (REC_ID)
    USING INDEX 
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE PHL_TXN_LOG ADD (
  CONSTRAINT PHL_TXN_LOG_PK
 PRIMARY KEY
 (REC_ID)
    USING INDEX 
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE PHC_VALUE ADD (
  CONSTRAINT PHC_VALUE_PK
 PRIMARY KEY
 (REC_ID)
    USING INDEX 
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE PHA_ALERT ADD (
  CONSTRAINT PHA_ALERT_PK
 PRIMARY KEY
 (REC_ID)
    USING INDEX 
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE PHC_CHARGE ADD (
  CONSTRAINT PHC_CHARGE_PK
 PRIMARY KEY
 (REC_ID)
    USING INDEX 
    TABLESPACE NSNDAT01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT DELETE, INSERT, SELECT ON PHA_ALERTS TO BERHANLIVE;

