
package com.neptunesoftwareplc.ci.account.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccountServiceImplService", targetNamespace = "http://service.account.ci.neptunesoftwareplc.com/", wsdlLocation = "file:/C:/Users/neptune/AppData/Local/Temp/tempdir7950613058022040430.tmp/AccountService_1.wsdl")
public class AccountServiceImplService
    extends Service
{

    private final static URL ACCOUNTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCOUNTSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ACCOUNTSERVICEIMPLSERVICE_QNAME = new QName("http://service.account.ci.neptunesoftwareplc.com/", "AccountServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/neptune/AppData/Local/Temp/tempdir7950613058022040430.tmp/AccountService_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOUNTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ACCOUNTSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AccountServiceImplService() {
        super(__getWsdlLocation(), ACCOUNTSERVICEIMPLSERVICE_QNAME);
    }

    public AccountServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTSERVICEIMPLSERVICE_QNAME, features);
    }

    public AccountServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTSERVICEIMPLSERVICE_QNAME);
    }

    public AccountServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTSERVICEIMPLSERVICE_QNAME, features);
    }

    public AccountServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccountService
     */
    @WebEndpoint(name = "AccountServiceImplPort")
    public AccountService getAccountServiceImplPort() {
        return super.getPort(new QName("http://service.account.ci.neptunesoftwareplc.com/", "AccountServiceImplPort"), AccountService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountService
     */
    @WebEndpoint(name = "AccountServiceImplPort")
    public AccountService getAccountServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.account.ci.neptunesoftwareplc.com/", "AccountServiceImplPort"), AccountService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ACCOUNTSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ACCOUNTSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
