
package com.neptunesoftwareplc.ci.account.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountService", targetNamespace = "http://service.account.ci.neptunesoftwareplc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.neptunesoftwareplc.ci.account.service.AccountBalanceResponseData
     * @throws CIException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAccountBalance", targetNamespace = "http://service.account.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.account.service.FindAccountBalance")
    @ResponseWrapper(localName = "findAccountBalanceResponse", targetNamespace = "http://service.account.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.account.service.FindAccountBalanceResponse")
    public AccountBalanceResponseData findAccountBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        AccountBalanceRequestData arg0)
        throws CIException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.neptunesoftwareplc.ci.account.service.AccountStatementOutputData
     * @throws CIException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAccountMiniStatement", targetNamespace = "http://service.account.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.account.service.FindAccountMiniStatement")
    @ResponseWrapper(localName = "findAccountMiniStatementResponse", targetNamespace = "http://service.account.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.account.service.FindAccountMiniStatementResponse")
    public AccountStatementOutputData findAccountMiniStatement(
        @WebParam(name = "arg0", targetNamespace = "")
        AccountStatementRequestData arg0)
        throws CIException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.neptunesoftwareplc.ci.account.service.LoanAccountResponseCIData
     * @throws CIException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAndActivateLoanAccount", targetNamespace = "http://service.account.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.account.service.CreateAndActivateLoanAccount")
    @ResponseWrapper(localName = "createAndActivateLoanAccountResponse", targetNamespace = "http://service.account.ci.neptunesoftwareplc.com/", className = "com.neptunesoftwareplc.ci.account.service.CreateAndActivateLoanAccountResponse")
    public LoanAccountResponseCIData createAndActivateLoanAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        LoanAccountRequestCIData arg0)
        throws CIException_Exception
    ;

}
