
package com.neptunesoftwareplc.ci.account.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CIException", targetNamespace = "http://service.account.ci.neptunesoftwareplc.com/")
public class CIException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CIException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CIException_Exception(String message, CIException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CIException_Exception(String message, CIException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.neptunesoftwareplc.ci.account.service.CIException
     */
    public CIException getFaultInfo() {
        return faultInfo;
    }

}
